# Generated by Django 2.2.13 on 2024-09-01 21:09

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=restaurants.models.EncryptedField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=restaurants.models.EncryptedField(blank=True, default='', max_length=252, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='environment',
            field=restaurants.models.EncryptedField(max_length=512),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='map_embed_url',
            field=restaurants.models.EncryptedField(default='https://maps.google.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=restaurants.models.EncryptedField(max_length=128),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
    ]
